CREATE TABLE USER (
	USERNAME VARCHAR(30) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(32) NOT NULL
);

CREATE TABLE BOARD (
	ID INTEGER NOT NULL PRIMARY KEY,
	SIZE_X INTEGER NOT NULL,
	SIZE_Y INTEGER NOT NULL,
	START_X INTEGER NOT NULL,
	START_Y INTEGER NOT NULL
);

CREATE TABLE GAME_BOARD (
	BOARD_ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
	OWNER VARCHAR(30) NOT NULL,
	FOREIGN KEY (BOARD_ID) REFERENCES BOARD(ID),
	FOREIGN KEY (OWNER) REFERENCES USER(USERNAME)
);



INSERT INTO USER VALUES('mrprez', '135db287cad29417f6cdea20b7e359a3');
INSERT INTO BOARD VALUES (1, 16, 16, 0, 0);
INSERT INTO BOARD VALUES (2, 32, 16, 2, 2);
INSERT INTO GAME_BOARD VALUES (1, 'test1','mrprez');
INSERT INTO GAME_BOARD VALUES (2, 'test2','mrprez');
